#ifndef DEMON_RETURN_VALUES
#define DEMON_RETURN_VALUES

typedef enum dmn_ret{
	UNKOWN_OP = 0,
	LOGIN_SUCCESS,
	LOGIN_INVALID_UN,
	LOGIN_INVALID_PWD,
	/*OTHER RETURN VALUES HERE*/
	

}DEMON_RETURN_STATUS;

#endif //DEMON_RETURN_VALUES